version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: securemail
    networks:
      - securemail-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - securemail-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432  # Note this is still 5432 internally
      - REDIS_HOST=redis
      - REDIS_PORT=6379  # Note this is still 6379 internally
    networks:
      - securemail-network

networks:
  securemail-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: